### ISSUE TITLE
May I use your data?

### ISSUE THREAD

**Issue by clozinski** [svaksha/pythonidae#9]
I run [Python Blogory](http://Blogory.org/python).   Until I found pythondae, I thought Blogory was the world's largest Python Direcotory. Now I am not sure.   I wonder how many links you have?

 May I use Pythondae data?  Blogory is a free service.

Regards
Chris

**Comment by svaksha** [comment]
Hi @clozinski, 
Thanks for asking. Yes, my repo is [licensed](https://github.com/svaksha/pythonidae#license) under 
the CC BY-NC-SA 4.0-International license, so as long as you attribute credit, I am fine with each section being linked to the various category sections in the markdown pages - For example, on your site the `Machine Learning (10)` section links to the `awesome-python` repo:
```
Libraries for Machine Learning. See: [awesome-machine-learning](https://github.com/josephmisiti/awesome-machine-learning#python).
```
The above example respects the CC BY-NC-SA 4.0-International license, so please go ahead :+1: and thanks!
